/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms.user;

import java.awt.Color;
import pms.util.jPanelLoader;

/**
 *
 * @author Rakib
 */
public class User extends javax.swing.JPanel {

    jPanelLoader jpl;

    /**
     * Creates new form AddInventory
     */
    public User() {
        initComponents();
        jpl = new jPanelLoader();
        AddUser add = new AddUser();
        jpl.jPanelLoader(userPanel, add);

        resetMenuBerColor();
        addUserPanel.setBackground(new Color(204, 204, 204));
        addUserLabel.setForeground(Color.BLACK);
    }

    private void resetMenuBerColor() {
        addUserPanel.setBackground(new Color(51, 51, 51));
        addUserLabel.setForeground(Color.WHITE);

        updateUserPanel.setBackground(new Color(51, 51, 51));
        updateUserLabel.setForeground(Color.WHITE);

        showUserPanel.setBackground(new Color(51, 51, 51));
        showUserLabel.setForeground(Color.WHITE);

        deleteUserPanel.setBackground(new Color(51, 51, 51));
        deleteUserLabel.setForeground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addUserPanel = new javax.swing.JPanel();
        addUserLabel = new javax.swing.JLabel();
        updateUserPanel = new javax.swing.JPanel();
        updateUserLabel = new javax.swing.JLabel();
        showUserPanel = new javax.swing.JPanel();
        showUserLabel = new javax.swing.JLabel();
        deleteUserPanel = new javax.swing.JPanel();
        deleteUserLabel = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new java.awt.GridLayout(0, 4));

        addUserPanel.setBackground(new java.awt.Color(51, 51, 51));
        addUserPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        addUserPanel.setPreferredSize(new java.awt.Dimension(272, 50));
        addUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserPanelMouseClicked(evt);
            }
        });

        addUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        addUserLabel.setText("Add User");

        javax.swing.GroupLayout addUserPanelLayout = new javax.swing.GroupLayout(addUserPanel);
        addUserPanel.setLayout(addUserPanelLayout);
        addUserPanelLayout.setHorizontalGroup(
            addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(addUserLabel)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        addUserPanelLayout.setVerticalGroup(
            addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(addUserPanel);

        updateUserPanel.setBackground(new java.awt.Color(51, 51, 51));
        updateUserPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        updateUserPanel.setPreferredSize(new java.awt.Dimension(272, 50));
        updateUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateUserPanelMouseClicked(evt);
            }
        });

        updateUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateUserLabel.setText("Update User");

        javax.swing.GroupLayout updateUserPanelLayout = new javax.swing.GroupLayout(updateUserPanel);
        updateUserPanel.setLayout(updateUserPanelLayout);
        updateUserPanelLayout.setHorizontalGroup(
            updateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateUserPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(updateUserLabel)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        updateUserPanelLayout.setVerticalGroup(
            updateUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(updateUserPanel);

        showUserPanel.setBackground(new java.awt.Color(51, 51, 51));
        showUserPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        showUserPanel.setPreferredSize(new java.awt.Dimension(272, 50));
        showUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUserPanelMouseClicked(evt);
            }
        });

        showUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        showUserLabel.setText("View User");

        javax.swing.GroupLayout showUserPanelLayout = new javax.swing.GroupLayout(showUserPanel);
        showUserPanel.setLayout(showUserPanelLayout);
        showUserPanelLayout.setHorizontalGroup(
            showUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showUserPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(showUserLabel)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        showUserPanelLayout.setVerticalGroup(
            showUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(showUserPanel);

        deleteUserPanel.setBackground(new java.awt.Color(51, 51, 51));
        deleteUserPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        deleteUserPanel.setPreferredSize(new java.awt.Dimension(272, 50));
        deleteUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserPanelMouseClicked(evt);
            }
        });

        deleteUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteUserLabel.setText("Delete User");

        javax.swing.GroupLayout deleteUserPanelLayout = new javax.swing.GroupLayout(deleteUserPanel);
        deleteUserPanel.setLayout(deleteUserPanelLayout);
        deleteUserPanelLayout.setHorizontalGroup(
            deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteUserPanelLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(deleteUserLabel)
                .addGap(79, 79, 79))
        );
        deleteUserPanelLayout.setVerticalGroup(
            deleteUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(deleteUserPanel);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        userPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        add(userPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserPanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        addUserPanel.setBackground(new Color(204, 204, 204));
        addUserLabel.setForeground(Color.BLACK);

        AddUser add = new AddUser();
        jpl.jPanelLoader(userPanel, add);
    }//GEN-LAST:event_addUserPanelMouseClicked

    private void updateUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserPanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        updateUserPanel.setBackground(new Color(204, 204, 204));
        updateUserLabel.setForeground(Color.BLACK);

        UpdateUser update = new UpdateUser();
        jpl.jPanelLoader(userPanel, update);
    }//GEN-LAST:event_updateUserPanelMouseClicked

    private void showUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserPanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        showUserPanel.setBackground(new Color(204, 204, 204));
        showUserLabel.setForeground(Color.BLACK);

        ViewUser view = new ViewUser();
        jpl.jPanelLoader(userPanel, view);
    }//GEN-LAST:event_showUserPanelMouseClicked

    private void deleteUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserPanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        deleteUserPanel.setBackground(new Color(204, 204, 204));
        deleteUserLabel.setForeground(Color.BLACK);

        DeleteUser delete = new DeleteUser();
        jpl.jPanelLoader(userPanel, delete);
    }//GEN-LAST:event_deleteUserPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addUserLabel;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JLabel deleteUserLabel;
    private javax.swing.JPanel deleteUserPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showUserLabel;
    private javax.swing.JPanel showUserPanel;
    private javax.swing.JLabel updateUserLabel;
    private javax.swing.JPanel updateUserPanel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
