package pms.empolyee;

import java.awt.Color;
import pms.util.jPanelLoader;

public class Employee extends javax.swing.JPanel {

    /**
     * Creates new form AddInventory
     */
    jPanelLoader jpl;

    public Employee() {
        initComponents();
        jpl = new jPanelLoader();
        AddEmployee addEmp = new AddEmployee();
        jpl.jPanelLoader(employeeMainPanel, addEmp);

        resetMenuBerColor();
        addEmployeePanel.setBackground(new Color(204, 204, 204));
        addEmployeeLabel.setForeground(Color.BLACK);
    }

    private void resetMenuBerColor() {
        addEmployeePanel.setBackground(new Color(51, 51, 51));
        addEmployeeLabel.setForeground(Color.WHITE);

        updateEmployeePanel.setBackground(new Color(51, 51, 51));
        updateEmployeeLabel.setForeground(Color.WHITE);

        ShowEmployeePanel.setBackground(new Color(51, 51, 51));
        showEmployeeLabel.setForeground(Color.WHITE);

        deleteEmployeePanel.setBackground(new Color(51, 51, 51));
        deleteEmployeeLabel.setForeground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addEmployeePanel = new javax.swing.JPanel();
        addEmployeeLabel = new javax.swing.JLabel();
        updateEmployeePanel = new javax.swing.JPanel();
        updateEmployeeLabel = new javax.swing.JLabel();
        ShowEmployeePanel = new javax.swing.JPanel();
        showEmployeeLabel = new javax.swing.JLabel();
        deleteEmployeePanel = new javax.swing.JPanel();
        deleteEmployeeLabel = new javax.swing.JLabel();
        employeeMainPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout(0, 4));

        addEmployeePanel.setBackground(new java.awt.Color(51, 51, 51));
        addEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        addEmployeePanel.setPreferredSize(new java.awt.Dimension(272, 50));
        addEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeePanelMouseClicked(evt);
            }
        });

        addEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addEmployeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeLabel.setText("Add Employee");

        javax.swing.GroupLayout addEmployeePanelLayout = new javax.swing.GroupLayout(addEmployeePanel);
        addEmployeePanel.setLayout(addEmployeePanelLayout);
        addEmployeePanelLayout.setHorizontalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(addEmployeeLabel)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        addEmployeePanelLayout.setVerticalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(addEmployeePanel);

        updateEmployeePanel.setBackground(new java.awt.Color(51, 51, 51));
        updateEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        updateEmployeePanel.setPreferredSize(new java.awt.Dimension(272, 50));
        updateEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateEmployeePanelMouseClicked(evt);
            }
        });

        updateEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateEmployeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateEmployeeLabel.setText("Update Employee");

        javax.swing.GroupLayout updateEmployeePanelLayout = new javax.swing.GroupLayout(updateEmployeePanel);
        updateEmployeePanel.setLayout(updateEmployeePanelLayout);
        updateEmployeePanelLayout.setHorizontalGroup(
            updateEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateEmployeePanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(updateEmployeeLabel)
                .addGap(53, 53, 53))
        );
        updateEmployeePanelLayout.setVerticalGroup(
            updateEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(updateEmployeePanel);

        ShowEmployeePanel.setBackground(new java.awt.Color(51, 51, 51));
        ShowEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        ShowEmployeePanel.setPreferredSize(new java.awt.Dimension(272, 50));
        ShowEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowEmployeePanelMouseClicked(evt);
            }
        });

        showEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showEmployeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        showEmployeeLabel.setText("View Employee");

        javax.swing.GroupLayout ShowEmployeePanelLayout = new javax.swing.GroupLayout(ShowEmployeePanel);
        ShowEmployeePanel.setLayout(ShowEmployeePanelLayout);
        ShowEmployeePanelLayout.setHorizontalGroup(
            ShowEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShowEmployeePanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(showEmployeeLabel)
                .addGap(61, 61, 61))
        );
        ShowEmployeePanelLayout.setVerticalGroup(
            ShowEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(ShowEmployeePanel);

        deleteEmployeePanel.setBackground(new java.awt.Color(51, 51, 51));
        deleteEmployeePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        deleteEmployeePanel.setPreferredSize(new java.awt.Dimension(272, 50));
        deleteEmployeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEmployeePanelMouseClicked(evt);
            }
        });

        deleteEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteEmployeeLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteEmployeeLabel.setText("Delete Employee");

        javax.swing.GroupLayout deleteEmployeePanelLayout = new javax.swing.GroupLayout(deleteEmployeePanel);
        deleteEmployeePanel.setLayout(deleteEmployeePanelLayout);
        deleteEmployeePanelLayout.setHorizontalGroup(
            deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteEmployeePanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(deleteEmployeeLabel)
                .addGap(56, 56, 56))
        );
        deleteEmployeePanelLayout.setVerticalGroup(
            deleteEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(deleteEmployeePanel);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        employeeMainPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout employeeMainPanelLayout = new javax.swing.GroupLayout(employeeMainPanel);
        employeeMainPanel.setLayout(employeeMainPanelLayout);
        employeeMainPanelLayout.setHorizontalGroup(
            employeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1088, Short.MAX_VALUE)
        );
        employeeMainPanelLayout.setVerticalGroup(
            employeeMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        add(employeeMainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeePanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        addEmployeePanel.setBackground(new Color(204, 204, 204));
        addEmployeeLabel.setForeground(Color.BLACK);

        AddEmployee addEmp = new AddEmployee();
        jpl.jPanelLoader(employeeMainPanel, addEmp);
    }//GEN-LAST:event_addEmployeePanelMouseClicked

    private void updateEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateEmployeePanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        updateEmployeePanel.setBackground(new Color(204, 204, 204));
        updateEmployeeLabel.setForeground(Color.BLACK);

        UpdateEmployee updateEmp = new UpdateEmployee();
        jpl.jPanelLoader(employeeMainPanel, updateEmp);
    }//GEN-LAST:event_updateEmployeePanelMouseClicked

    private void ShowEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowEmployeePanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        ShowEmployeePanel.setBackground(new Color(204, 204, 204));
        showEmployeeLabel.setForeground(Color.BLACK);

        ViewEmployee viewEmp = new ViewEmployee();
        jpl.jPanelLoader(employeeMainPanel, viewEmp);
    }//GEN-LAST:event_ShowEmployeePanelMouseClicked

    private void deleteEmployeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEmployeePanelMouseClicked
        // TODO add your handling code here:
        resetMenuBerColor();
        deleteEmployeePanel.setBackground(new Color(204, 204, 204));
        deleteEmployeeLabel.setForeground(Color.BLACK);

        DeleteEmployee deleteEmp = new DeleteEmployee();
        jpl.jPanelLoader(employeeMainPanel, deleteEmp);
    }//GEN-LAST:event_deleteEmployeePanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ShowEmployeePanel;
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.JPanel addEmployeePanel;
    private javax.swing.JLabel deleteEmployeeLabel;
    private javax.swing.JPanel deleteEmployeePanel;
    private javax.swing.JPanel employeeMainPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showEmployeeLabel;
    private javax.swing.JLabel updateEmployeeLabel;
    private javax.swing.JPanel updateEmployeePanel;
    // End of variables declaration//GEN-END:variables
}
